### ISSUE TITLE
Removing nodes sometimes resulsts in a crash

### ISSUE THREAD

**Issue by heroin-moose** [hroi/treebitmap#7]
Hi,

I'm still trying to get more details but this code:

```
extern crate treebitmap;

use std::net::Ipv4Addr;

use treebitmap::IpLookupTable;

fn main() {
    let mut table: IpLookupTable<Ipv4Addr, ()> = IpLookupTable::new();

    println!("len: {}", table.len());

    table.insert("2.93.185.24".parse().unwrap(), 32, ());
    table.insert("2.93.200.133".parse().unwrap(), 32, ());

    println!("len: {}", table.len());

    table.remove("2.93.185.24".parse().unwrap(), 32);
    table.remove("2.93.200.133".parse().unwrap(), 32);

    println!("len: {}", table.len());
}
```

results in a crash:

```
$  cargo build
   Compiling test v0.1.0 (file:///tmp/test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
$ RUST_BACKTRACE=1 ./target/debug/test 
len: 0
len: 2
thread 'main' panicked at 'tried to free non-empty collection', /home/consus/.cargo/registry/src/github.com-1ecc6299db9ec823/treebitmap-0.3.1/src/tree_bitmap/allocator.rs:334:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:445
   6: <treebitmap::tree_bitmap::allocator::Allocator<T>>::free
             at ./<panic macros>:3
   7: <treebitmap::tree_bitmap::TreeBitmap<T>>::remove_child
             at /home/consus/.cargo/registry/src/github.com-1ecc6299db9ec823/treebitmap-0.3.1/src/tree_bitmap/mod.rs:324
   8: <treebitmap::tree_bitmap::TreeBitmap<T>>::remove_child
             at /home/consus/.cargo/registry/src/github.com-1ecc6299db9ec823/treebitmap-0.3.1/src/tree_bitmap/mod.rs:317
   9: <treebitmap::tree_bitmap::TreeBitmap<T>>::remove_child
             at /home/consus/.cargo/registry/src/github.com-1ecc6299db9ec823/treebitmap-0.3.1/src/tree_bitmap/mod.rs:317
  10: <treebitmap::tree_bitmap::TreeBitmap<T>>::remove_child
             at /home/consus/.cargo/registry/src/github.com-1ecc6299db9ec823/treebitmap-0.3.1/src/tree_bitmap/mod.rs:317
  11: <treebitmap::tree_bitmap::TreeBitmap<T>>::remove_child
             at /home/consus/.cargo/registry/src/github.com-1ecc6299db9ec823/treebitmap-0.3.1/src/tree_bitmap/mod.rs:317
  12: <treebitmap::tree_bitmap::TreeBitmap<T>>::remove
             at /home/consus/.cargo/registry/src/github.com-1ecc6299db9ec823/treebitmap-0.3.1/src/tree_bitmap/mod.rs:288
  13: <treebitmap::IpLookupTable<A, T>>::remove
             at /home/consus/.cargo/registry/src/github.com-1ecc6299db9ec823/treebitmap-0.3.1/src/lib.rs:108
  14: test::main
             at src/main.rs:17
  15: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  20: main
  21: __libc_start_main
  22: _start
```

**Comment by heroin-moose** [comment]
P.S. Tests pass fine, though.

**Comment by heroin-moose** [comment]
Any news?

**Comment by hroi** [comment]
The fix by @jiegec has been merged.
